apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-etyp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-docker-python-rhtap-three-component-scenarios-etyp
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-docker-python-rhtap-three-component-scenarios-etyp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-etyp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-etyp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnem-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-etyp@sha256:b272a32ddc55cc97e7f71c47c9090d89a26d11f0a4bab1c5952bcaa08b17d8a0
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
