apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-aomm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-nodevfile-nodocker-rhtap-three-component-scenarios-aomm
    app.kubernetes.io/part-of: mc-three-scenarios
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-aomm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-aomm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-aomm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnem-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-aomm@sha256:e25d6e477aedbd6fb4206d791ce416d27ebe2353c14e8ce5c16c4a9bdbe56c21
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
